apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kong-teste-teste-teste"
  annotations:
    backstage.io/techdocs-ref: dir:.
    vault.io/secrets-path: devportal
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/admin"
